# Copyright (c) 2019-2021, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

include:
  - .common-ci.yml

# build-all jobs build packages for every OS / ARCH combination we support.
#
# They are run under two conditions:
# 1) Automatically whenever a new tag is pushed to the repo (e.g. v1.1.0)
# 2) Manually by a reviewer just before merging a MR.
.build-all-for-arch:
  variables:
    # Setting DIST=docker invokes the docker- release targets
    DIST: docker
  extends:
    - .package-build
  stage: build-all
  timeout: 2h 30m
  rules:
    - if: $CI_COMMIT_TAG
      when: always

# The full set of build-all jobs organized to
# have builds for each ARCH run in parallel.
build-all-amd64:
  extends:
    - .build-all-for-arch
    - .arch-amd64

build-all-x86_64:
  extends:
    - .build-all-for-arch
    - .arch-x86_64

build-all-ppc64le:
  extends:
    - .build-all-for-arch
    - .arch-ppc64le

build-all-arm64:
  extends:
    - .build-all-for-arch
    - .arch-arm64

build-all-aarch64:
  extends:
    - .build-all-for-arch
    - .arch-aarch64
